### ISSUE TITLE
Add a tile system for the environment

### ISSUE THREAD

**Issue by AdrianWennberg** [ucdnetsoc/BrassLands#9]
Tiles are essential for grid based movement, so this system is going to be central to the game. We can start with something simple for now and expand on this later. There are at least two types of tiles that we will probably need to start off with: the walls and the floors.

I think pre generated maps of only floors and walls would be a good start. these need to be stored and drawn on to the screen, and we need to make sure the player cannot walk through walls.

**Comment by DavidPHH** [comment]
Is there anything left for this? #15 pretty much covers it I think

**Comment by AdrianWennberg** [comment]
Yeah, you're right @dphennessy. I'll go ahead and close this.
